name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-3-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build rspec-3.1
      - run: docker compose run rspec-3.1

  build-3-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build rspec-3.2
      - run: docker compose run rspec-3.2

  build-3-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build rspec-3.3
      - run: docker compose run rspec-3.3

  build-3-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build rspec-3.4
      - run: docker compose run rspec-3.4
